name = "scroll-gateway-worker"
account_id = "15dcc9085cb794bb4f29d3e8177ac880"
main = "./src/worker.ts"
node_compat = true
compatibility_date = "2023-10-13"


[dev]
port = 8080

[build]
command = "yarn build"

[env.sepolia]
name = "scroll-sepolia-gateway-worker"
